[2024-10-09T10:29:07.250+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-09T10:29:07.266+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_01.run_concat_container_C1 manual__2024-10-09T10:15:27.346552+00:00 [queued]>
[2024-10-09T10:29:07.273+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_01.run_concat_container_C1 manual__2024-10-09T10:15:27.346552+00:00 [queued]>
[2024-10-09T10:29:07.273+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-09T10:29:07.284+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_concat_container_C1> on 2024-10-09 10:15:27.346552+00:00
[2024-10-09T10:29:07.290+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=548) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-09T10:29:07.291+0000] {standard_task_runner.py:72} INFO - Started process 549 to run task
[2024-10-09T10:29:07.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_01', 'run_concat_container_C1', 'manual__2024-10-09T10:15:27.346552+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpj1bav0i1']
[2024-10-09T10:29:07.294+0000] {standard_task_runner.py:105} INFO - Job 147: Subtask run_concat_container_C1
[2024-10-09T10:29:07.335+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_01.run_concat_container_C1 manual__2024-10-09T10:15:27.346552+00:00 [running]> on host a4706156eccf
[2024-10-09T10:29:07.406+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_01' AIRFLOW_CTX_TASK_ID='run_concat_container_C1' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T10:15:27.346552+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T10:15:27.346552+00:00'
[2024-10-09T10:29:07.406+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-09T10:29:07.425+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-09T10:29:07.428+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-09T10:29:08.030+0000] {docker.py:438} INFO - Data concatenated successfully into data.csv.
[2024-10-09T10:29:08.285+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-09T10:29:08.285+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_01, task_id=run_concat_container_C1, run_id=manual__2024-10-09T10:15:27.346552+00:00, execution_date=20241009T101527, start_date=20241009T102907, end_date=20241009T102908
[2024-10-09T10:29:08.308+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-09T10:29:08.337+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-09T10:29:08.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
