[2024-10-26T22:27:11.604+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T22:27:11.620+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_01.run_concat_container_C1 manual__2024-10-26T22:12:23.442491+00:00 [queued]>
[2024-10-26T22:27:11.628+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_01.run_concat_container_C1 manual__2024-10-26T22:12:23.442491+00:00 [queued]>
[2024-10-26T22:27:11.629+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-26T22:27:11.640+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_concat_container_C1> on 2024-10-26 22:12:23.442491+00:00
[2024-10-26T22:27:11.647+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1177) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T22:27:11.648+0000] {standard_task_runner.py:72} INFO - Started process 1178 to run task
[2024-10-26T22:27:11.649+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_01', 'run_concat_container_C1', 'manual__2024-10-26T22:12:23.442491+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpklcyigml']
[2024-10-26T22:27:11.649+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask run_concat_container_C1
[2024-10-26T22:27:11.685+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_01.run_concat_container_C1 manual__2024-10-26T22:12:23.442491+00:00 [running]> on host bacd1900a50a
[2024-10-26T22:27:11.755+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_01' AIRFLOW_CTX_TASK_ID='run_concat_container_C1' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T22:12:23.442491+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T22:12:23.442491+00:00'
[2024-10-26T22:27:11.756+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T22:27:11.790+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-26T22:27:11.793+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-26T22:27:12.297+0000] {docker.py:438} INFO - Data concatenated successfully into data.csv.
[2024-10-26T22:27:12.473+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T22:27:12.473+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_01, task_id=run_concat_container_C1, run_id=manual__2024-10-26T22:12:23.442491+00:00, execution_date=20241026T221223, start_date=20241026T222711, end_date=20241026T222712
[2024-10-26T22:27:12.507+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T22:27:12.530+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T22:27:12.531+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
